coachup/config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'register' => 'users#new', as: 'register'

  get 'overview/welcome'

  resources :users do
    resources :courses, only: [:index]
    resources :subscriptions do
      get 'coaches', action: 'coaches_index', on: :collection
      get 'coaches/courses', action: 'coaches_courses_index', on: :collection
    end

    get 'delete_avatar', :action => :delete_avatar
    member do
      put 'like', to: 'users#upvote'
      put 'dislike', to: 'users#downvote'
    end
  end

  resources :courses do
    post 'apply', :action => :apply
    post 'leave', :action => :leave
    get 'export', :action => :export
  end

  get '/auth/facebook/callback', to: 'users#link_facebook'
  delete '/auth/facebook', to: 'users#unlink_facebook'
  get '/auth/:provider/callback', to: 'sessions#token'
  get '/auth/failure', to: 'sessions#omniauth_failure'

  get '/partnerships/', to: 'my_partnerships#index', as: 'partnerships'
  post '/partnerships/:username', to: 'my_partnerships#create', as: 'partnership'
  delete '/partnerships/:username', to: 'my_partnerships#destroy'
  get '/partnerships/courses', to: 'my_partnerships#courses_index', as: 'partnerships_courses'

  root 'overview#root'

end

coachup/app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

coachup/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @user = User.find params[:user_id]
    @courses = @user.courses
  end

  def create
    @subscription = Subscription.new(subscription_params)
    @subscription.user = current_user

    if @subscription.save
      redirect_to @subscription
    else
      render 'new'
    end
  end

  def destroy
  end

  def coaches_index
    @user = User.find params[:user_id]
    @coaches = get_coaches @user
  end

  def coaches_courses_index
    coaches_index
    @courses = Course.where(coach: @coaches)
  end

  private

  def get_coaches(user)
    coaches = []
    user.subscriptions.find_each do |subscription|
      unless coaches.include?(subscription.course.coach)
        coaches << subscription.course.coach
      end
    end
    coaches
  end

  def subscription_params
    params.require(:subscription).permit(:course_id, :user_id)
  end
end

coachup/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

coachup/app/views/subscriptions/coaches_courses_index.html.erb
<% if current_user == @user %>
  <%= render partial: 'courses/index', locals: {
      title: 'Courses given by your coaches',
      empty_text: 'None of your coaches gives any courses right now...'
  } %>
<% else %>
  <%= render partial: 'courses/index', locals: {
      title: "Courses given by coaches of #{@user.username}",
      empty_text: "None of the coaches of #{@user.username} gives any courses right now..."
  } %>
<% end %>

coachup/app/views/subscriptions/coaches_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
        Coaches of <%= @user.username %>
      </h3>
    </div>
  </div>
  <% if @coaches.present? %>
      <%= render partial: 'users/user', collection: @coaches %>
  <% else %>
      <h4><%= @user.username %> doesn't have any coaches yet...</h4>
  <% end %>
</div>

coachup/app/views/subscriptions/index.html.erb
<% if @user == current_user %>
    <%= render partial: 'courses/index', locals: {
        title: 'Courses you are taking',
        empty_text: 'You are not taking any courses yet...'
    } %>
<% else %>
    <%= render partial: 'courses/index', locals: {
        title: "Courses taken by #{@user.username}",
        empty_text: "#{@user.username} doesn't take any courses yet..."
    } %>
<% end %>

coachup/app/views/subscriptions/my_coaches_index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h3 class="page-header"> My Coaches </h3>
  </div>
  <% if @my_coaches.present? %>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th>Coach</th>
              <th>Email</th>
            </tr>
            </thead>
            <tbody>

            <% @my_coaches.each do |coach| %>

                <tr>
                  <td><%= coach.username %></td>
                  <td><%= coach.email %></td>
                  <td><%= link_to 'Show', user_path(coach) %></td>

                  <td><%= link_to 'Edit', edit_course_path(coach) %></td>
                  <td><%= link_to 'Destroy', course_path(coach),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %> </td>
                </tr>
            <% end %>

            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-6 -->
  <% else %>
      <h4>You have no coaches yet...</h4>
  <% end %>
</div>

coachup/app/views/subscriptions/my_partnerships_index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        My Partnerships
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table">
            <thead>
            <tr>
              <th>Coach</th>
              <th>Email</th>
            </tr>
            </thead>
            <tbody>

            <% @partnerships.each do |subscription| %>

                <tr>

                  <td><%= subscription.username %></td>
                  <td><%= subscription.email %></td>
                  <td><%= link_to 'Show', subscription_path(subscription) %></td>

                  <td><%= link_to 'Edit', edit_course_path(subscription) %></td>
                  <td><%= link_to 'Destroy', course_path(subscription),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %> </td>
                </tr>
            <% end %>

            </tbody>
          </table>
        </div>
        <!-- /.table-responsive -->
      </div>
      <!-- /.panel-body -->
    </div>
    <!-- /.panel -->
  </div>
  <!-- /.col-lg-6 -->
</div>