coachup/config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'register' => 'users#new', as: 'register'

  get 'overview/welcome'

  resources :users do
    resources :courses, only: [:index]
    resources :subscriptions do
      get 'coaches', action: 'coaches_index', on: :collection
      get 'coaches/courses', action: 'coaches_courses_index', on: :collection
    end

    get 'delete_avatar', :action => :delete_avatar
    member do
      put 'like', to: 'users#upvote'
      put 'dislike', to: 'users#downvote'
    end
  end

  resources :courses do
    post 'apply', :action => :apply
    post 'leave', :action => :leave
    get 'export', :action => :export
  end

  get '/auth/facebook/callback', to: 'users#link_facebook'
  delete '/auth/facebook', to: 'users#unlink_facebook'
  get '/auth/:provider/callback', to: 'sessions#token'
  get '/auth/failure', to: 'sessions#omniauth_failure'

  get '/partnerships/', to: 'my_partnerships#index', as: 'partnerships'
  post '/partnerships/:username', to: 'my_partnerships#create', as: 'partnership'
  delete '/partnerships/:username', to: 'my_partnerships#destroy'
  get '/partnerships/courses', to: 'my_partnerships#courses_index', as: 'partnerships_courses'

  root 'overview#root'

end

coachup/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_votable
  acts_as_voter

  has_many :taught_courses, class_name: 'Course', foreign_key: 'coach_id'
  has_many :subscriptions
  has_many :courses, through: :subscriptions

  attr_accessor :realname, :publicvisible, :password_confirmation,
                :new_password, :new_password_confirmation, :avatar,
                :avatar_cache, :delete_avatar

  validates :realname, presence: true
  validates :email, email: true
  # creating user
  validates :username, presence: true, length: { within: 3..50 }, uniqueness: true
  validates :password, length: { within: 3..50 }, confirmation: true, on: :create
  # editing user
  validates :new_password, length: { within: 3..50 }, confirmation: true, if: :new_password_present?, on: :update
  validates :phone, phone: true, on: :update

  mount_uploader :avatar, AvatarUploader

  def get_next_sessions
    date_course = Struct.new(:date, :course)
    all_dates = Set.new
    subscriptions.each do |sub|
      schedule = sub.course.retrieve_schedule
      occ = schedule.occurrences(sub.course.ends_at)
      occ.each do |date|
        element = date_course.new
        element.date = date
        element.course = sub.course
        all_dates.add(element) if element.date.start_time >= Time.current
      end
    end

    all_dates = all_dates.sort_by(&:date)
    all_dates.take(10)
  end

  def approval_rate
    return 100 if votes_for.size == 0
    (get_upvotes.size.to_f / votes_for.size) * 100
  end

  def subscribed_to_course_from?(user)
    subs = subscriptions
    return false if subs.nil?
    subs.each do |sub|
      return true if sub.course.coach == user
    end
    false
  end

  private

  def new_password_present?
    new_password.present?
  end
end

coachup/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :require_authorization, only: [:edit, :update, :destroy]
  skip_before_action :require_login, except: [:edit, :update, :destroy, :upvote, :downvote, :delete_avatar,
                                              :link_facebook, :unlink_facebook]

  def index
    @users = User.all
  end

  def show
    if @user.facebook_uid
      @facebook_url = 'https://www.facebook.com/' + @user.facebook_uid
    end
    return unless user_signed_in?
    partnership = CoachClient::Partnership.new(coach_client,
                                               current_user.username,
                                               @user.username)
    partnership.user1.password = session[:password]
    begin
      partnership.update
      @is_following = partnership.user1_confirmed
    rescue CoachClient::Exception
      @is_following = false
    end
  end

  def new
    @user = User.new
  end

  def edit
    coach_user = CoachClient::User.new(coach_client, session[:username],
                                       password: session[:password])
    coach_user.update
    @user = current_user
    @user.realname = coach_user.realname
    @user.publicvisible = coach_user.publicvisible
  end

  def create
    # Note: This transaction may have a big impact on performance
    User.transaction do
      @user = User.new(user_params)
      if @user.save
        coach_user = CoachClient::User.new(coach_client, @user.username,
                                           password: @user.password,
                                           email: @user.email,
                                           realname: @user.realname,
                                           publicvisible: 2)
        begin
          coach_user.save
        rescue CoachClient::Exception => e
          unless @user.avatar
            Cloudinary::Api.delete_resources(@user.avatar.file.public_id)
          end
          msg = if e.is_a?(CoachClient::Unauthorized)
                  "User #{@user.username} already exists"
                else
                  "Could not create new user"
                end
          redirect_to register_path, alert: msg
          raise ActiveRecord::Rollback
        end
        session[:username] = @user.username
        session[:password] = @user.password
        redirect_to root_path, notice: "Successfully created user #{@user.username}"
      else
        render 'new'
      end
    end
  end

  def update
    # Note: This transaction may have a big impact on performance
    @user = current_user
    User.transaction do
      if @user.update(user_params)
        coach_user = CoachClient::User.new(coach_client, session[:username],
                                           password: session[:password],
                                           email: @user.email,
                                           realname: @user.realname)
        if @user.new_password.present?
          coach_user.newpassword = @user.new_password
          # Ugly fix
          @user.update_column :password, @user.new_password
        end

        begin
          coach_user.save
        rescue CoachClient::Exception
          flash[:alert] = "Could not save changes"
          render 'edit'
          raise ActiveRecord::Rollback
        end
        flash[:notice] = "Successfully updated profile"
        session[:password] = @user.new_password if @user.new_password.present?
        redirect_to user_path(current_user)
      else
        render 'edit'
      end
    end
  end

  def destroy
  end

  def delete_avatar
    @user = current_user
    Cloudinary::Api.delete_resources(@user.avatar.file.public_id)
    @user.remove_avatar = true
    @user.update_attribute(:avatar, nil)
    @user.reload

    redirect_to edit_user_path @user
  end

  def link_facebook
    # TODO: require_login (fix skip_before_action)
    auth = env['omniauth.auth']
    current_user.update_column :facebook_uid, auth.uid
    flash[:notice] = "Your profile is now linked to your facebook account"
    redirect_to user_path(current_user)
  end

  def unlink_facebook
    current_user.update_column :facebook_uid, nil
    flash[:notice] = "Your profile isn't link to any facebook account anymore"
    redirect_to user_path(current_user)
  end

  def upvote
    @user.upvote_by current_user
    redirect_to user_path(@user)
  end

  def downvote
    @user.downvote_by current_user
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
    @username = session[:username]
    @password = session[:password]
  end

  def require_authorization
    user = User.find(params[:id])
    redirect_to user_path unless user && current_user == user
  end

  def user_params
    params.require(:user).permit(:username, :password, :realname, :email,
                                 :publicvisible, :password_confirmation,
                                 :address, :country, :phone, :date_of_birth, :education, :bio, :aboutme,
                                 :new_password, :new_password_confirmation, :avatar, :avatar_cache, :delete_avatar)
  end
end

coachup/app/helpers/users_helper.rb
module UsersHelper
  def full_name(username)
    user = User.find_by(username: username)
    return nil if user.nil?

    begin
      coach_user = CoachClient::User.new(coach_client, username, password: user.password)
      coach_user.update
      coach_user.realname
    rescue CoachClient::Exception
      nil
    end
  end
end

coachup/app/views/users/_edit_form.html.erb
<div class="row">
  <%= render "errors" %>

  <div class="col-lg-6">
    <%= form_for(@user, url: { action: 'update' }, html: { role: 'form' }) do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :realname %>
        <%= f.text_field :realname, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :country %>
        <%= f.text_field :country, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :phone %>
        <%= f.telephone_field :phone, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :date_of_birth %>
        <div class="input-group date" id="datepicker">
          <%= f.text_field :date_of_birth, class: 'form-control', value: @user.date_of_birth.try(:strftime,'%d-%m-%Y'), placeholder: '01-01-2000' %>
          <span class="input-group-addon">
            <i class="glyphicon glyphicon-calendar"></i>
          </span>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :education %>
        <%= f.text_field :education, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :bio %>
        <%= f.text_area :bio, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :aboutme %>
        <%= f.text_field :aboutme, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :new_password %>
        <%= f.password_field :new_password, placeholder: 'leave blank if unchanged', autocomplete: 'off', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :new_password_confirmation %>
        <%= f.password_field :new_password_confirmation, placeholder: 'leave blank if unchanged', autocomplete: 'off', class: 'form-control' %>
      </div>

      <div class="form-group">
        <% if @user.avatar? %>
        <%= f.label :avatar, 'Profile Picture' %><br>
        <%= image_tag @user.avatar_url(:display, :class=>"profile-image") %><br>
        <%= link_to 'Remove Picture', user_delete_avatar_path(@user), :controller => :users, data: {confirm: 'Would you like to delete your avatar?'} %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :avatar, 'New Picture' %>
        <%= f.file_field :avatar %>
        <% f.hidden_field :avatar_cache %>
      </div>

      <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-lg btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(function() {
    $('#datepicker').datetimepicker({
        format: 'DD-MM-YYYY',
        viewMode: 'years',
        minDate: '01/01/1890',
        maxDate: Date.now()
    });
  });
</script>

coachup/app/views/users/_errors.html.erb
<% if @user && @user.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @user.errors.each do |attr, msg| %>
        <% if @user.errors[attr].first == msg %>
          <li><%= "#{attr.to_s.gsub('_', ' ').capitalize!} #{msg}" %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

coachup/app/views/users/_form.html.erb
<div class="row">
  <%= render "errors" %>

  <div class="col-lg-6">
    <%= form_for(@user, url: { action: 'create' }, html: { role: 'form' }) do |f| %>
      <div class="form-group">
        <%= f.label :username %>
        <%= f.text_field :username, autofocus: true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :realname %>
        <%= f.text_field :realname, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: 'off', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :avatar, 'Profile Picture' %>
        <%= f.file_field :avatar %>
        <% f.hidden_field :avatar_cache %>
      </div>

      <div class="form-group">
        <%= f.submit 'Create', class: 'btn btn-lg btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

coachup/app/views/users/_user.html.erb
<div class="box-info text-center user-profile-2">
  <div class="header-cover"></div>
  <div class="user-profile-inner">
    <h5 class="white">
      <%= full_name(user.username) or 'Unknown Name' %>
    </h5>
    <% if user.avatar_url.present? %>
        <%= image_tag user.avatar_url(:display), class: 'img-circle profile-avatar' %>
    <% else %>
        <%= cl_image_tag('default', class: 'img-circle profile-avatar') %>
    <% end %>

    <h5><em><%= user.username %></em></h5>
    <div class="row">
      <div class="col-xs-12 col-sm-12">
        <%= link_to  user_path(user.id), class: 'btn btn-primary btn-sm btn-block' do %>
            <span class="glyphicon glyphicon-user"></span>
            View Profile
        <% end %>
      </div>
    </div>
  </div>
</div>

coachup/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">Edit User</h2>
    </div>
  </div>
  <%= render 'edit_form' %>
</div>

coachup/app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <h3 class="page-header">
       Users Profiles
      </h3>
    </div>
  </div>

  <%= render partial: 'users/user', collection: @users %>

</div>

coachup/app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">Create User</h2>
    </div>
  </div>
  <%= render 'form' %>
</div>

coachup/app/views/users/show.html.erb
<%= stylesheet_link_tag 'profile-theme.min' %>
<div class="container-fluid view-profile">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="page-header">
        <% if user_signed_in? && current_user == @user %>
            My Profile
        <% else %>
            <%= @user.username %>'s Profile
        <% end %>
      </h2>
    </div>

  </div>

    <!-- start: Content -->
    <div id="content">

      <div class="row profile">

        <div class="col-md-3">

          <div class="row">
            <div class="col-sm-7 col-md-12 avatar">
              <% if @user.avatar_url.present? %>
                <%= image_tag @user.avatar_url(:display), class: 'profile-image' %>
              <% else %>
                <%= image_tag cloudinary_url('default', height: 200, width: 200, crop: :fill),
                              class: 'profile-image' %>
              <% end %>
            </div>
            <div class="col-sm-5 col-md-12">

              <% if user_signed_in? && current_user != @user %>
                <% if @is_following %>
                    <%= link_to fa_icon('star lg fw', text: 'Unfavorite'),
                                partnership_path(@user.username), method: :delete,
                                class: 'btn btn-default button-follow', role: 'button' %>
                <% else %>
                    <%= link_to fa_icon('star-o lg fw', text: 'Favorite'),
                                partnership_path(@user.username), method: :post,
                                class: 'btn btn-default button-follow', role: 'button' %>
                <% end %>
                </br>
                <% if current_user.subscribed_to_course_from? @user %>
                  <% case current_user.voted_as_when_voted_for @user %>
                  <% when true %>
                    <%= link_to fa_icon('thumbs-up lg', text: 'Liked'), '#', role: 'button',
                          class: 'btn btn-sm btn-success button-appreciation disabled' %>
                    <%= link_to fa_icon('thumbs-down lg', text: 'Dislike'),
                          dislike_user_path(@user), method: :put, role: 'button',
                          class: 'btn btn-sm btn-danger button-appreciation' %>
                  <% when false %>
                    <%= link_to fa_icon('thumbs-up lg', text: 'Like'),
                          like_user_path(@user), method: :put, role: 'button',
                          class: 'btn btn-sm btn-success button-appreciation' %>
                    <%= link_to fa_icon('thumbs-down lg', text: 'Disliked'), '#', role: 'button',
                          class: 'btn btn-sm btn-danger button-appreciation disabled' %>
                  <% when nil %>
                    <%= link_to fa_icon('thumbs-up lg', text: 'Like'),
                          like_user_path(@user), method: :put, role: 'button',
                          class: 'btn btn-sm btn-success button-appreciation' %>
                    <%= link_to fa_icon('thumbs-down lg', text: 'Dislike'),
                          dislike_user_path(@user), method: :put, role: 'button',
                          class: 'btn btn-sm btn-danger button-appreciation' %>
                  <% end %>
                <% end %>
              <% end %>
              <p class="approval"><%= @user.approval_rate %> % (<%= @user.votes_for.size %> votes)</p>
              <h3>General Information</h3>
              <ul class="profile-details">
                <li>
                  <div><i class="fa fa-user"></i> Full Name </div>
                  <%= full_name(@user.username) %>
                </li>
                <li>
                  <div><i class="fa fa-briefcase"></i> Education</div>
                  <%= @user.education %>
                </li>
                <li>
                <li>
                  <div><i class="fa fa-birthday-cake"></i> Date Of Birth</div>
                  <%= @user.date_of_birth %>
                </li>
                <li>
                  <div><i class="fa fa-facebook"></i> Facebook Profile</div>
                  <% if @facebook_url %>
                    <%= link_to 'Verified', @facebook_url %>
                    <% if current_user == @user %>
                      <br/>
                      <%= link_to 'Unlink your account', auth_facebook_path,
                                  method: :delete %>
                    <% end %>
                  <% elsif current_user == @user %>
                    <%= link_to 'Verify your account with Facebook',
                                auth_facebook_path %>
                  <% else %>
                    <i>Not verified</i>
                  <% end %>
                </li>
              </ul>

              <h3>Contact Information</h3>

              <ul class="profile-details">
                <li>
                  <div><i class="fa fa-phone"></i> Phone</div>
                    <%= @user.phone %>
                </li>
                <li>
                  <div><i class="fa fa-envelope"></i> E-mail</div>
                  <%= @user.email %>
                </li>
                <li>
                  <div><i class="fa fa-map-marker"></i> Address</div>
                  <%= @user.address %>, <%= @user.country %>
                </li>
              </ul>
            </div>
          </div><!--/row-->

        </div><!--/col-->

        <div class="col-md-9">

          <ul class="nav nav-tabs" id="myTab">
            <% if current_user == @user  %>
                <%= button_to "Edit Profile", edit_user_path, :class => "btn btn-primary pull-right", :method => :get  %>
            <% end %>
            <li class="active"><%= link_to 'Skills', user_path(@user.id) %></li>
            <li>
              <%= link_to 'Taught Courses', user_courses_path(@user.id) %>
            </li>
          </ul>

          <div class="tab-content">
            <div class="tab-pane active" id="skills">

              <div class="row">
                <div class="col-sm-8">
                  <h2>About Me</h2>
                  <%= @user.aboutme %></p>

                  <h2>Bio</h2>
                  <p><%= @user.bio %></p>

                </div><!--/col-->

              </div><!--/row-->

            </div>
          </div>

        </div><!--/col-->

      </div><!--/profile-->

    </div>
    <!-- end: Content -->

</div><!--/container-->