coachup/config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: 'logout'
  get 'register' => 'users#new', as: 'register'

  get 'overview/welcome'

  resources :users do
    resources :courses, only: [:index]
    resources :subscriptions do
      get 'coaches', action: 'coaches_index', on: :collection
      get 'coaches/courses', action: 'coaches_courses_index', on: :collection
    end

    get 'delete_avatar', :action => :delete_avatar
    member do
      put 'like', to: 'users#upvote'
      put 'dislike', to: 'users#downvote'
    end
  end

  resources :courses do
    post 'apply', :action => :apply
    post 'leave', :action => :leave
    get 'export', :action => :export
  end

  get '/auth/facebook/callback', to: 'users#link_facebook'
  delete '/auth/facebook', to: 'users#unlink_facebook'
  get '/auth/:provider/callback', to: 'sessions#token'
  get '/auth/failure', to: 'sessions#omniauth_failure'

  get '/partnerships/', to: 'my_partnerships#index', as: 'partnerships'
  post '/partnerships/:username', to: 'my_partnerships#create', as: 'partnership'
  delete '/partnerships/:username', to: 'my_partnerships#destroy'
  get '/partnerships/courses', to: 'my_partnerships#courses_index', as: 'partnerships_courses'

  root 'overview#root'

end

coachup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coachup</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Google Maps external scripts -->
  <%= javascript_include_tag '//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry' %>
  <%= javascript_include_tag '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag("logo.png", :width => 150, :height => 35) %>
      <% end %>
    </div>
    <!-- /.navbar-header -->

    <!-- #nav-profile-links -->
    <ul class="nav navbar-nav navbar-right navbar-collapse collapse" id="nav-profile-links">
      <% if user_signed_in? %>
        <%= menu_item current_user.username, user_path(current_user) %>
      <% else %>
        <%= menu_item fa_icon('user-plus fw', text: 'Sign Up'), register_path %>
        <%= menu_item fa_icon('sign-in fw', text: 'Log In'), login_path %>
      <% end %>
      <%= drop_down fa_icon('user fw lg') do %>
      <% if user_signed_in? %>
          <%= menu_item fa_icon('user fw', text: 'Edit Profile'),
                        edit_user_path(current_user) %>
          <%= drop_down_divider %>
          <%= menu_item fa_icon('sign-out fw', text: 'Log Out'), logout_path %>
        <% else %>
          <%= menu_item fa_icon('user-plus fw', text: 'Sign Up'), register_path %>
          <%= drop_down_divider %>
          <%= menu_item fa_icon('sign-in fw', text: 'Log in'), login_path %>
        <% end %>
      <% end %>
    </ul>
    <!-- /#nav-profile-links -->

    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse collapse">
        <ul class="nav" id="side-menu">
          <li class="sidebar-search">
            <%= form_tag courses_path, method: "get" do %>
                <div class="input-group">
                  <%= search_field_tag 'q[title_or_description_cont]', nil, class: "form-control", placeholder: "Search courses...",
                                       value: params[:q] && params[:q][:title_or_description_cont]|| ""%>
                  <span class="input-group-btn">
                <%= submit_tag 'Search', class: "btn btn-default" %>
              </span>
                </div><!-- /input-group -->
            <% end %>
            <!-- /input-group -->
          </li>
          <li>
            <%= link_to fa_icon('book fw', text: 'Courses Overview'), courses_path %>
          </li>
          <% if user_signed_in? %>
            <li>
              <a id="courses_button" href="#">
                <%= fa_icon('bars fw', text: 'Courses') %><span class="fa arrow"></span>
              </a>
              <ul class="nav nav-second-level collapse" id="courses_submenu">
                <li>
                  <%= link_to fa_icon('book fw', text: 'Courses Taken'),
                              user_subscriptions_path(current_user) %>
                </li>
                <li>
                  <%= link_to fa_icon('book fw', text: 'Courses Given'),
                              user_courses_path(current_user) %>
                </li>
                <li>
                  <%= link_to fa_icon('book fw', text: 'Courses By My Coaches'),
                                      coaches_courses_user_subscriptions_path(current_user) %>
                </li>
                <li>
                  <%= link_to fa_icon('book fw', text: 'Courses By My Favorites'),
                              partnerships_courses_path %>
                </li>
              </ul>
              <!-- /.nav-second-level -->
            </li>
            <li>
              <%= link_to fa_icon('graduation-cap fw', text: 'My Coaches'),
                          coaches_user_subscriptions_path(current_user) %>
            </li>
            <li>
              <%= link_to fa_icon('star fw', text: 'My Favorite Coaches'),
                          partnerships_path %>
            </li>
          <% end %>
          <li>
            <%= link_to fa_icon('users fw', text: 'Users Profiles'), users_path%>
          </li>


        <% if user_signed_in? %>
            <li>

              <a href="#"><%= fa_icon('calendar fw', text: 'Upcoming Sessions') %>
                <input type="checkbox" data-size="mini" name="my-checkbox"checked>
              </a>
            </li><br>
            <div id="session" style="display: none;">
              <ul class="event-list">
            <% sessions = current_user.get_next_sessions %>
              <% if sessions == false %>
                  <%= link_to 'Apply for a course!' , courses_path %>
              <% elsif !sessions.nil? %>
                <% sessions.each do |session| %>
                  <%= link_to course_path(session.course) do%>
                    <li>
                      <time datetime="2014-07-20">
                        <span class="day"><%= session.date.strftime("%d") %> </span>
                        <span class="month"><%= session.date.strftime("%b") %></span>
                      </time>
                      <div class="info">
                        <h2 class="title"> <%= session.course.title %></h2>
                      </div>
                      <div class="social">
                        <ul>
                          <li>
                            <span class="glyphicon glyphicon-chevron-right "></span>
                          </li>
                        </ul>
                      </div>
                    </li>
                  <% end %>
                <% end %>
              <% else %>
                  <%= 'You have no sessions within a year!' %>
              <% end %>
              </ul>
            </div>
        <% end %>
        </ul>
      </div>
      <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
  </nav>

  <div id="page-wrapper">
    <% if notice %>
        <p class="alert alert-success cancel-wrapper-margin"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger cancel-wrapper-margin"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>
  <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<script type="text/javascript">
$(document).ready(function() {

  function process_switch(event, state) {
    $("#session").toggle(state);
    Cookies.set('show_upcoming_sessions', state);
  }
  $("[name='my-checkbox']").on('switchChange.bootstrapSwitch', process_switch);

  var initial_state = Cookies.getJSON('show_upcoming_sessions');
  if (initial_state === undefined) initial_state = true;
  $("[name='my-checkbox']").bootstrapSwitch('state', initial_state, true);
  process_switch(null, initial_state);
});
</script>
</body>
</html>